"""Persistence boundaries for runs, observations, and normalized leads."""

from datetime import datetime
from pathlib import Path
from typing import Protocol
from uuid import UUID

from linkedin_automation.domain.models import (
    ConnectionRequest,
    Lead,
    Observation,
    OutreachRecord,
    ResearchRun,
    SentMessage,
)


class ResearchRepository(Protocol):
    """Durable storage required by application workflows."""

    def initialize(self) -> None: ...

    def close(self) -> None: ...

    def add_run(self, run: ResearchRun) -> None: ...

    def save_run(self, run: ResearchRun) -> None: ...

    def get_run(self, run_id: UUID) -> ResearchRun | None: ...

    def add_observation(self, observation: Observation) -> None: ...

    def upsert_lead(self, lead: Lead) -> bool: ...

    def list_leads(self, run_id: UUID) -> list[Lead]: ...

    def get_lead(self, lead_id: UUID) -> Lead | None: ...

    def upsert_outreach(self, record: OutreachRecord) -> None: ...

    def get_outreach(self, lead_id: UUID) -> OutreachRecord | None: ...

    def list_outreach(self, run_id: UUID) -> list[OutreachRecord]: ...

    def add_connection_request(self, request: ConnectionRequest) -> None: ...

    def list_connection_requests(self, run_id: UUID) -> list[ConnectionRequest]: ...

    def count_connection_requests_since(self, since: datetime) -> int: ...

    def add_sent_message(self, message: SentMessage) -> None: ...

    def list_sent_messages(self, run_id: UUID) -> list[SentMessage]: ...

    def count_sent_messages_since(self, since: datetime) -> int: ...

    def count_observations_since(self, since: datetime) -> int: ...

    def database_path(self) -> Path: ...
